theme: jekyll-theme-cayman
google_analytics: G-TJ7SDSPJ1V
title: NJ COVID-19 Vaccination Simplified Location Guide
description: This page simplifies the information from the official NJ location list into a format that’s easier to act on.
twitter:
    username:          dantasfiles
    card:              summary
